SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[rep_bdx_riskdata](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Branch] [int] NOT NULL,
	[ClientRef] [varchar](20) NOT NULL,
	[PolicyRef] [varchar](20) NOT NULL,
	[RecordNumber] [int] NOT NULL,
	[Name][varchar](255) NOT NULL,
	[InsurerPolicyRef] [varchar](50) NULL,
	[Insurer] [varchar](50) NULL,
	[PolicyType] [varchar](2) NOT NULL,
	[Version] [int] NOT NULL,
	[DateOfEntry] [datetime] NOT NULL,
	[InceptionDate] [datetime] NOT NULL,
	[EffectiveDate] [datetime] NOT NULL,
	[ChangeReason] [varchar](50) NOT NULL,
	[TransType] [varchar](50) NOT NULL,
	[RiskAddress] [varchar](max) NOT NULL,
	[PostCode] [varchar](10) NULL,
	[YearOfAccount] [int] NULL,
	[HomeBuildingsSI] [int] NULL,
	[HomeBuildingsPrem] [decimal](11, 2) NULL,
	[HomeContentsSI] [int] NULL,
	[HomeContentsPrem] [decimal](11, 2) NULL,
	[HomePersonalPossSI] [int] NULL,
	[HomePersonalPossPrem] [decimal](11, 2) NULL,
	[FineArtSI] [int] NULL,
	[FineArtPrem] [decimal](11, 2) NULL,
	[LegalExpensesSI] [int] NULL,
	[LegalExpensesPrem] [decimal] NULL,
	[TravelPrem] [decimal] NULL,
	[PropertyDamageBuildingsSI] [int] NULL,
	[PropertyDamageBuildingsPrem] [decimal](11, 2) NULL,
	[PropertyDamageContentsSI] [int] NULL,
	[PropertyDamageContentsPrem] [decimal](11, 2) NULL,
	[LossOfRevenueSI] [int] NULL,
	[LossOfRevenuePrem] [decimal](11, 2) NULL,
	[LivestockSI] [int] NULL,
	[LivestockPrem] [decimal](11, 2) NULL,
	[LivestockARMSI] [int] NULL,
	[LivestockARMPrem] [decimal](11, 2) NULL,
	[DiseaseSI] [int] NULL,
	[DiseasePrem] [decimal](11, 2) NULL,
	[EmployersLiabilitySI] [int] NULL,
	[EmployersLiabilityPrem] [decimal](11, 2) NULL,
	[PublicLiabilitySI] [int] NULL,
	[PublicLiabilityPrem] [decimal](11, 2) NULL,
	[EnvironmentalLiabilitySI] [int] NULL,
	[EnvironmentalLiabilityPrem] [decimal](11, 2) NULL,
	[PersonalAccidentSI] [int] NULL,
	[PersonalAccidentPrem] [decimal](11, 2) NULL,
	[GoodsInTransitSI] [int] NULL,
	[GoodsInTransitPrem] [decimal](11, 2) NULL,
	[AllRisksSI] [int] NULL,
	[AllRisksPrem] [decimal](11, 2) NULL,
	[MoneySI] [int] NULL,
	[MoneyPrem] [decimal](11, 2) NULL,
	[CARSI] [int] NULL,
	[CARPrem] [decimal](11, 2) NULL,
	[TerrorismSI] [int] NULL,
	[TerrorismPrem] [decimal](11, 2) NULL,
	[BrokeragePctl] [float] NULL,
	[BrokerageAmount] [float] NULL,
	[NetPremium] [float] NULL,
	[TotalPremium] [float] NULL,
	[IPT] [float] NULL,
	[AmountDueToInsurers] [float] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

