SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[rep_bdx_ledger_test](
	[Branch@] [int] NOT NULL,
	[Key@] [varchar](28) NOT NULL,
	[ClientRef@] [varchar](6) NULL,
	[PolicyRef@] [varchar](10) NULL,
	[Suffix@] [int] NULL,
	[Polref] [varchar](10) NULL,
	[Poltype] [varchar](2) NULL,
	[Suffix] [int] NULL,
	[Trantype] [varchar](14) NULL,
	[Paymethod] [varchar](1) NULL,
	[Dt_raised] [datetime] NULL,
	[Dt_settled] [datetime] NULL,
	[Orig_debt] [decimal](10, 2) NULL,
	[Poac] [decimal](10, 2) NULL,
	[Status] [int] NULL,
	[Chg_ptr] [int] NULL,
	[Ltr_ptr] [int] NULL,
	[Ledger_dt] [datetime] NULL,
	[#Ref] [varchar](6) NULL,
	[Instal_amt] [decimal](10, 2) NULL,
	[Instal_dt] [datetime] NULL,
	[Instal_freq] [varchar](7) NULL,
	[Remarks] [varchar](50) NULL,
	[Comm_amt] [decimal](10, 2) NULL,
	[Pay_dt] [datetime] NULL,
	[Samt] [decimal](10, 2) NULL,
	[C_ptr] [int] NULL,
	[M_c_amt] [decimal](10, 2) NULL,
	[C_ins_INSC_VTId] [int] NULL,
	[C_mast] [int] NULL,
	[C_comm] [decimal](8, 4) NULL,
	[C_prop] [decimal](6, 2) NULL,
	[C_disc] [decimal](5, 2) NULL,
	[C_polno] [varchar](18) NULL,
	[M_c_comm] [decimal](10, 2) NULL,
	[Polref_s] [varchar](4) NULL,
	[Ccode] [int] NULL,
	[Shared_prem] [varchar](3) NULL,
	[No_of_units] [int] NULL,
	[Remarks_2] [varchar](50) NULL,
	[Gross_exempt] [decimal](10, 2) NULL,
	[Ipt_rate] [decimal](6, 3) NULL,
	[Ipt_amount] [decimal](9, 2) NULL,
	[Cca_req] [varchar](3) NULL,
	[Sorig_debt] [decimal](11, 2) NULL,
	[Ref_suffix] [varchar](4) NULL,
	[Int_ptr] [int] NULL,
	[Pcl_charge] [decimal](9, 2) NULL,
	[Pcl_status] [varchar](25) NULL,
	[Pcl_transmit_dt] [datetime] NULL,
	[F_pcl] [decimal](12, 0) NULL,
	[F_bacs] [decimal](12, 0) NULL,
	[F_dapremcalc] [decimal](12, 0) NULL,
	[F_ddposted] [decimal](12, 0) NULL,
	[F_lestop] [decimal](12, 0) NULL,
	[F_commctrl] [decimal](12, 0) NULL,
	[F_invstop] [decimal](12, 0) NULL,
	[F_invreq] [decimal](12, 0) NULL,
	[F_unconfirmed] [decimal](12, 0) NULL,
	[F_statement] [decimal](12, 0) NULL,
	[F_feesettle] [decimal](12, 0) NULL,
	[F_chaserflag] [decimal](12, 0) NULL,
	[F_dueflag] [decimal](12, 0) NULL,
	[F_papersdue] [decimal](12, 0) NULL,
	[Remarks_3] [varchar](50) NULL,
	[Remarks_4] [varchar](50) NULL,
	[Le_o_prem] [decimal](10, 2) NULL,
	[Create_opcode] [varchar](2) NULL,
	[Agent_pay_dt] [datetime] NULL,
	[Agent_comm] [decimal](10, 2) NULL,
	[Yoa] [int] NULL,
	[Lockdown] [datetime] NULL,
	[F_agent_comm] [decimal](12, 0) NULL,
	[Pf_transmit_dt] [datetime] NULL,
	[Add_master] [varchar](4) NULL,
	[F_add_haveaddons] [decimal](12, 0) NULL,
	[#Key] [varchar](14) NULL,
	[Payer] [varchar](5) NULL,
	[Agent] [varchar](4) NULL,
	[#Exec] [varchar](4) NULL,
	[Datecreated] [datetime] NULL,
	[Operator] [varchar](2) NULL,
	[Insurer_INSC_VTId] [int] NULL,
	[Agent_paytype] [varchar](5) NULL,
	[Enddate] [datetime] NULL,
	[Ref_prefix] [varchar](2) NULL,
	[Dt_eol] [datetime] NULL,
	[Dt_termsagreed] [datetime] NULL,
	[Dt_evidence] [datetime] NULL,
	[Insfee] [decimal](8, 2) NULL,
	[Eol_insurer_INSC_VTId] [int] NULL,
	[Insfee_ipt] [varchar](3) NULL,
	[Insfee_comm] [varchar](3) NULL,
	[Cashbook_dt] [datetime] NULL,
	[Cashbook_time] [varchar](5) NULL,
	[Old_int_ptr] [int] NULL,
	[Tax_type] [varchar](7) NULL,
	[Bkr_rcpts] [varchar](13) NULL,
	[Ultins01_INSU_VTId] [int] NULL,
	[Ultins02_INSU_VTId] [int] NULL,
	[Ultins03_INSU_VTId] [int] NULL,
	[Ultins04_INSU_VTId] [int] NULL,
	[Ultins05_INSU_VTId] [int] NULL,
	[Ultins06_INSU_VTId] [int] NULL,
	[Ultins07_INSU_VTId] [int] NULL,
	[Ultins08_INSU_VTId] [int] NULL,
	[Ultins09_INSU_VTId] [int] NULL,
	[Ultins10_INSU_VTId] [int] NULL,
	[Filler2] [varchar](16) NULL,
	[Agent_comm_paid] [decimal](10, 2) NULL,
	[No_def_ultins] [varchar](3) NULL,
	[Import_diary_note] [int] NULL,
	[Apm_created] [varchar](3) NULL,
	[RefreshGenerationId] [int] NULL,
	[LastUpdatedTime] [datetime] NULL
) ON [PRIMARY]

GO

